spring.application.name=seguranca
spring.datasource.url=jdbc:mysql://localhost:3306/trabalho_mvc
spring.datasource.username=root
spring.datasource.password=6778
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
api.security.token.secret=segurancareforcadapelos2ou3homensqueescreveramissomasfoiso1